### PR TITLE
Language corrections

### PR DESCRIPTION
**Pull request by FiveYellowMice**
This may help you improve your English.

### CODE REVIEW

**Comment by K-Guan** [comment]
fan zheng you bu shi kan bu dong.

**Comment by FiveYellowMice** [comment]
But incorrect grammar leads to misunderstanding, confusion, uncomfort and shows unsophistication of the developer..

**Comment by K-Guan** [comment]
If I disagree, I won't merge this commit.

**Comment by FiveYellowMice** [comment]
You are right.

**Comment by pigfromChina** [comment]
为什么不用中文 speak Chinese please😉

**Comment by K-Guan** [comment]
@pigfromChina +1 about your id.

**Pull request merged**
